name: Composite Action Demo

on:
  workflow_dispatch:

jobs:
  java-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Run Java build action
        uses: ./.github/actions/java-build
        with:
          java-version: '21'