name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_ENV: ${{ vars.APP_ENV}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Show environment
        run: echo "Running in $APP_ENV environment"

      - name: Build Application
        run: ./mvnw package -DskipTests

      - name: Upload application artifact
        uses: actions/upload-artifact@v5
        with:
          name: application.jar
          path: target/*.jar

  unit-test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run unit Tests
        run: ./mvnw test

  integration-test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run integration Tests
        run: ./mvnw verify

  package:
    needs: [unit-test, integration-test]
    runs-on: ubuntu-latest

    steps:
      - name: Download application artifact
        uses: actions/download-artifact@v5
        with:
          name: application.jar
          path: target

      - name: List downloaded files
        run: ls -l target

  deploy-dev:
    needs: package
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Show deployment environment
        run: echo "Deploying to ${{vars.APP_ENV}}"