name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.version.outputs.app-version }}

    env:
      APP_ENV: ${{ vars.APP_ENV}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Show environment
        run: echo "Running in $APP_ENV environment"

      - name: Set Application Version
        id: version
        run: echo "app-version=1.0.0" >> "  $GITHUB_OUTPUT"

      - name: Build Application
        run: ./mvnw package -DskipTests

      - name: Upload application artifact
        uses: actions/upload-artifact@v5
        with:
          name: application.jar
          path: target/*.jar

  build-status:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Show build information
        run: echo "Build result is ${{ needs.build.result }}"

      - name: Show Application version
        run: echo "Application version is ${{needs.build.outputs.app-version}}"

  unit-test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run unit Tests
        run: ./mvnw test

      - name: Report failure
        if: failure()
        run: echo "A previous step in this job failed"

      - name: Always run
        if: always()
        run: echo "This step always runs"

  integration-test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run integration Tests
        run: ./mvnw verify

  package:
    needs: [unit-test, integration-test]
    runs-on: ubuntu-latest

    steps:
      - name: Download application artifact
        uses: actions/download-artifact@v5
        with:
          name: application.jar
          path: target

      - name: List downloaded files
        run: ls -l target

  deploy-dev:
    needs: package
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Show deployment environment
        run: echo "Deploying to ${{vars.APP_ENV}}"